# Generated by Django 3.2.16 on 2024-02-21 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес')),
                ('unit_of_measurement', models.CharField(choices=[('гр', 'грамм'), ('мл', 'миллилитр'), ('шт', 'штука'), ('чл', 'чайная ложка'), ('сл', 'столовая ложка')], max_length=2, verbose_name='Единица измерения')),
                ('kkal', models.PositiveSmallIntegerField(verbose_name='Ккал')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='calories.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('name',),
                'default_related_name': 'products',
            },
        ),
        migrations.CreateModel(
            name='EatenProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес')),
                ('unit_of_measurement', models.CharField(choices=[('гр', 'грамм'), ('мл', 'миллилитр'), ('шт', 'штука'), ('чл', 'чайная ложка'), ('сл', 'столовая ложка')], max_length=2, verbose_name='Единица измерения')),
                ('kkal', models.PositiveSmallIntegerField(verbose_name='Ккал')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления продукта')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eaten_products', to='calories.category', verbose_name='Категория')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eaten_products', to='calories.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eaten_products', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'съеденный продукт',
                'verbose_name_plural': 'съеденные продукты',
                'ordering': ('-publication_date',),
                'default_related_name': 'eaten_products',
            },
        ),
    ]
