# Generated by Django 3.2.16 on 2024-02-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eatenproduct',
            old_name='kkal',
            new_name='kсal',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='kkal',
            new_name='kсal',
        ),
    ]
