# Generated by Django 3.2.16 on 2024-02-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_auto_20240221_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eatenproduct',
            old_name='kсal',
            new_name='kcal',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='kсal',
            new_name='kcal',
        ),
    ]
